---
- name: Ensure /opt/dgraph directory exists
  path:
    path: "{{ dgraph_install_dir }}"
    state: directory
    owner: "root"
    group: "root"
    mode: "0755"

- name: Ensure /opt/dgraph/data directory exists
  file:
    path: "{{ item }}"
    state: directory
    owner: "root"
    group: "root"
    mode: "0755"
  loop:
    - "/var/lib/dgraph/zero"
    - "/var/lib/dgraph/alpha"

- name: Download dgraph tarball
  get_url:
    url: "https://github.com/dgraph-io/dgraph/releases/download/{{ dgraph_version }}/dgraph-{{ dgraph_version }}-linux-amd64.tar.gz"
    dest: "/tmp/dgraph.tar.gz"
    mode: "0755"

- name: Extract dgraph tarball
  unarchive:
    src: "/tmp/dgraph.tar.gz"
    dest: "{{ dgraph_install_dir }}"
    owner: "root"
    group: "root"
    mode: "0755"
    remote_src: true
  register: extract_result
  changed_when: extract_result.changed

- name: Remove dgraph tarball
  file:
    path: "/tmp/dgraph.tar.gz"
    state: absent

- name: Ensure dgraph binary is executable
  file:
    path: "{{ dgraph_install_dir }}/dgraph"
    mode: "0755"
    owner: "root"
    group: "root"

- name: Deploy dgraph-zero service files
  template:
    src: "dgraph-zero.service.j2"
    dest: "/etc/systemd/system/dgraph-zero.service"
    owner: "root"
    group: "root"
    mode: "0644"
  notify: Reload systemd and restart dgraph-zero

- name: Deploy dgraph-alpha service files
  template:
    src: "dgraph-alpha.service.j2"
    dest: "/etc/systemd/system/dgraph-alpha.service"
    owner: "root"
    group: "root"
    mode: "0644"
  notify: Reload systemd and restart dgraph-alpha

- name: Reload systemd and restart dgraph-zero
  systemd:
    daemon_reload: true
    state: restarted
    name: dgraph-zero

- name: Reload systemd and restart dgraph-alpha
  systemd:
    daemon_reload: true
    state: restarted
    name: dgraph-alpha

- name: Ensure dgraph-zero is running
  systemd:
    name: dgraph-zero
    state: started

- name: Ensure dgraph-alpha is running
  systemd:
    name: dgraph-alpha
    state: started

- name: Ensure dgraph-zero is enabled
  systemd:
    name: dgraph-zero
    enabled: true

- name: Ensure dgraph-alpha is enabled
  systemd:
    name: dgraph-alpha
    enabled: true

