- name: Remove specific line from /etc/hosts
  hosts: containerd_nodes
  become: true
  become_method: sudo
  vars:
    ansible_ssh_private_key_file: ~/.ssh/id_rsa_k8s
    ansible_python_interpreter: /usr/bin/python3.10

  tasks:
    - name: Remove the line with the node's IP and hostname from /etc/hosts
      lineinfile:
        path: /etc/hosts
        state: absent
        regexp: "{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }} {{ inventory_hostname }}"

    - name: Remove the line with 127.0.1.1 and hostname from /etc/hosts
      lineinfile:
        path: /etc/hosts
        state: absent
        regexp: "127.0.1.1 {{ ansible_host }}"
