---
# Global settings
os: "linux"
arch: "amd64"
ansible_user: "ansible"
ansible_ssh_private_key_file: "~/.ssh/id_rsa"
ansible_python_interpreter: "/usr/bin/python3"

# Airflow settings
airflow_version: "2.9.3"  # Specify your desired Airflow version
python_version: "3.9"     # Python version for virtual environment
airflow_user: "airflow"
airflow_group: "airflow"
airflow_home: "/opt/airflow"
venv_path: "{{ airflow_home }}/venv"
airflow_config_path: "{{ airflow_home }}/airflow.cfg"
airflow_logs_path: "{{ airflow_home }}/logs"
airflow_dags_path: "{{ airflow_home }}/dags"
airflow_plugins_path: "{{ airflow_home }}/plugins"

# KùzuDB on Rocky Linux
kuzu_user: "kuzu"
kuzu_version: "0.9.0"
kuzu_download_url: "https://github.com/kuzudb/kuzu/releases/download/v{{ kuzu_version }}/kuzu_cli-linux-x86_64.tar.gz"
kuzu_install_dir: "/opt/kuzu"
kuzu_service_name: "kuzudb"
kuzu_data_dir: "{{ kuzu_install_dir }}/data"
kuzu_port: 1664

# External database settings (example for PostgreSQL)
airflow_db:
  engine: "postgresql"
  host: "your-db-host"  # Replace with your DB host
  port: "5432"
  name: "airflow"
  user: "airflow"
  password: "your-secure-password"  # Replace with secure password

# Airflow connection string
airflow_sql_alchemy_conn: "{{ airflow_db.engine }}://{{ airflow_db.user }}:{{ airflow_db.password }}@{{ airflow_db.host }}:{{ airflow_db.port }}/{{ airflow_db.name }}"

# dgraph settings
dgraph_version: "23.1.1"
dgraph_install_dir: "/opt/dgraph"

# dgraph zero settings
dgraph_zero_host: "192.168.1.68"
dgraph_zero_grpc_port: 5080
dgraph_zero_data_dir: "/var/lib/dgraph/zero"
dgraph_zero_bindall: true
dgraph_zero_replicas: 1

# dgraph alpha settings
dgraph_alpha_host: "192.168.1.68"
dgraph_alpha_grpc_port: 9080
dgraph_alpha_data_dir: "/var/lib/dgraph/alpha"
dgraph_alpha_bindall: true


# Airflow Certificate settings
airflow_server_hostname: "airflow.example.com"  # Replace with your server's hostname
airflow_cert_root_ca: "/etc/ssl/certs/root-ca.crt"
airflow_cert_intermediate_ca: "/etc/ssl/certs/ca2.crt"
airflow_cert_server_crt: "/etc/ssl/certs/airflow-server.crt"
airflow_cert_server_pem: "/etc/ssl/certs/airflow-server.pem"
airflow_cert_server_key: "/etc/ssl/private/airflow-server.key"
airflow_cert_chain: "/etc/ssl/certs/airflow-server-chain.crt"